image: $CI_REGISTRY/sourceengineers/playground/container-armgcc:97c82ac5

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - all

examples:
  stage: all
  # Prevent dubious ownership alerts
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
  script:
    - cmake --workflow --preset ci-example
    - cmake --workflow --preset ci-example-string-replacement
    - cmake --install build/x86_64/release --component examples
    - cmake --install build/x86_64/string_replacment --component example-string-replacement
  artifacts:
    name: binaries-examples-${CI_COMMIT_SHA}
    paths:
      - release
    expire_in: 1 day


unit-tests:
  stage: all
  script:
    - cmake --workflow --preset ci-test
    - cmake --install build/x86_64/test --component tests
    - mkdir -p release/report/coverage
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o release/report/se-oss-coverage-report.xml --html --html-theme github.dark-green --html-details release/report/coverage/index.html --root ${CI_PROJECT_DIR} -e '/.*/build/' -e '/.*/test/' -e '/usr*' -e '/.*/lib/'
  artifacts:
    name: unit-test-${CI_COMMIT_SHA}
    reports:
      junit: release/report/se-oss-test-report.xml
      coverage_report:
        coverage_format: cobertura
        path: release/report/se-oss-coverage-report.xml
    paths:
      - release
    expire_in: 1 day
